alias ls='ls --color=auto'
alias l='ls -la'
alias ld='ls -lDa'
alias grep='grep --color=auto'
alias update='sudo pacman -Syu; ~/suckless/slstatus/updatePkgCount.sh'
alias add='myfunction() { sudo pacman -S $@; ~/suckless/slstatus/updatePkgCount.sh; }; myfunction'
alias remove='myfunction() { sudo pacman -Rns $@; ~/suckless/slstatus/updatePkgCount.sh; }; myfunction'
alias search='sudo pacman -Ss'
alias programs='sudo pacman -Qe'
alias c='clear'
alias gc='git commit'
alias ga='git add'
alias gs='git status'
alias mount='mount |column -t'
alias ff='fastfetch'
alias audio='pulsemixer'
alias jobs='crontab -l'
alias editjobs='crontab -e'
alias wp='~/Scripts/setRandomWallpaper.sh'
alias prop='xprop'
alias mirror='xrandr --output DP-2 --mode 1920x1080 --rate 240 --left-of HDMI-0'
alias smci='sudo make clean install'
alias nnn='nnn -e'
alias suspend='systemctl suspend'
alias n='nvim'
alias sn='sudo nvim'
alias snc='sudo nvim config.h'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
